"""empty message

Revision ID: 395570b55008
Revises: d62d5e10e7f8
Create Date: 2022-08-27 08:34:05.845618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395570b55008'
down_revision = 'd62d5e10e7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_stripe', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'id_stripe')
    # ### end Alembic commands ###
